### ISSUE TITLE
Window gets stuck when moving to next display and a full screen app is open on external monitor

### ISSUE THREAD

**Issue by montoulieu** [rxhanson/Rectangle#120]
macOS version:
Catalina 10.15.4

Rectangle version:
0.25

So I have 2 external monitors that I use with my MacBook Pro.

I've consistenly noticed for several versions of Rectangle that if I try to move a window to the next/previous display while a full screen app is up on one of my external monitors, it'll prevent the window from moving across displays. 

When I switch spaces in mission control on the monitor that had the full screen app open, I can see that the window I was moving is there on one of the desktops.

A fix on this would be greatly appreciated, this is the only inconsistency I've found moving from Spectacle. Thanks for all your work on this!

**Comment by rxhanson** [comment]
Thanks for posting. I've actually looked into what Spectacle does for moving to displays where there is a full screen app, and there is no difference in the logic between Spectacle and Rectangle for this scenario. Here's the issue where I explained my findings: https://github.com/rxhanson/Rectangle/issues/51. 

Can you describe what behavior you previously experienced on Spectacle that is different?

Also, what is your expected behavior? Is it that the window jumps past the display with the full-screened app?

**Comment by montoulieu** [comment]
Sorry for my delayed response @rxhanson!

Here's a imgur video of the issue with my setup: [https://imgur.com/a/QlgmV4g](https://imgur.com/a/QlgmV4g)

You can see the terminal window on my bottom screen is able to move to next/prev display perfectly for monitors that don't have a full screen app open.

But as soon as I move it to a display that is in full screen mode, the app gets stuck on that monitor and can no longer change displays.

When i open mission control and switch to the first desktop on that display, I can see that the app is waiting there in the background.

Hope that helps!

**Comment by rxhanson** [comment]
@montoulieu thanks for taking the time to make a video! 

On the previous Spectacle behavior, did your window appear in front of the full-screened app on that display?

Was your previous experience with Spectacle on the current version of macOS as well?

The reason I ask is because there really isn't anything special that Spectacle does for this - I can't find a difference between the two apps here, so it's possible that it's a change in macOS behavior. 

I can definitely see where this would be annoying, but I don't have the bandwidth to add any type of fix in for this one at the moment. To me, it would make the most sense to add the logic that skips over a display if it has a fullscreen app, as mentioned in https://github.com/rxhanson/Rectangle/issues/51.  The change shouldn't be hard to roll into the `ScreenDetection` class, as long as it turns out to be straightforward determining if a screen has a fullscreen app on it.

**Comment by montoulieu** [comment]
Of course, glad to help.

I just reinstalled spectacle app and it seems to move the windows behind the full screen apps, but they don’t get locked into a desktop screen the way Rectangle does, so it allows it to at least return to the un-full screened display.

Yeah the solution you mentioned towards the end of your last comment would be even better than Spectacle because it wouldn’t cause windows do just disappear without knowing where they even are.

Appreciate your time on this!

**Comment by rxhanson** [comment]
Been a while since this was reported, but I released [v0.37](https://github.com/rxhanson/Rectangle/releases/tag/v0.37) that has different behavior relative to this issue. Now when a window is moved to a display with a full screened app, the window will be refocused, so the fullscreened app will be unfocused in lieu of the desktop with the moved window. 

This is different from my initial thought to skip full screened displays, but I think it's a little more intuitive for most use cases.

Feel free to comment or reopen if there's an issue with v0.37+

**Comment by montoulieu** [comment]
Hey @rxhanson, just gave the v0.38 another download on the latest Catalina version and I'm still seeing the same behavior described in the original comment.

I've been using Spectacle in the mean time which doesn't seem to be affected.
Hope to use this someday as it's a really clean app.
Let me know if I can be of any help debugging.
👍
