### ISSUE TITLE
Snapping doesn't work the first time

### ISSUE THREAD

**Issue by jdarpinian** [rxhanson/Rectangle#1572]
- [X] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 15.3.1
Rectangle version: Pro 3.0.46 (187)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): I'll try to get a log next time it happens

Somewhat frequently when I move a window snapping does not work. If I let go of the window and move it a second time, snapping works. May be related to connecting a monitor, though I haven't figured out reliable repro steps.

**Comment by rxhanson** [comment]
Thanks for reporting. Does this happen for all apps, or only specific ones?

**Comment by jdarpinian** [comment]
I think it has happened with Cursor and Chrome, both Chromium based of course. Not sure if it happens with other apps.

**Comment by jdarpinian** [comment]
I figured out how to repro. It's related to the macOS "double click a window's title bar to [Fill]" feature. If you have the native feature enabled and double click to fill, then drag the filled window, Rectangle will not snap it. Of course if you use the equivalent Rectangle feature then there is no bug, but you lose the window size animation that the native feature has.

**Comment by jdarpinian** [comment]
And it happens with any app.

**Comment by rxhanson** [comment]
Thanks for figuring that out! I'll work on this for the next release.

**Comment by rxhanson** [comment]
This should be fixed in v0.87. Let me know if it's not.

**Comment by jdarpinian** [comment]
It's fixed, thank you!

**Comment by jdarpinian** [comment]
Hmm, after using it for a while it's definitely better but I still see some issues. If I drag a filled window to the edge too quickly then either it doesn't snap or it snaps for a fraction of a second and then unsnaps. Probably related to the shrinking animation that restores the original size of the window when you start dragging it. If I drag slowly then the animation has time to finish and snapping works as expected.

**Comment by rxhanson** [comment]
Thanks for the update. This is due to the animation, in the sense that Rectangle does not know if the window is being moved or resized until macOS gives it updated window dimensions. Off the top of my head, I don't know of a good way around this provided what is available to 3rd parties. Out of curiosity, are you choosing the macOS double click toolbar functionality because of the animation or because of the different size adjustments (it doesn't always maximize)?

**Comment by jdarpinian** [comment]
Yeah, that makes sense. I like the animation (one of the rare Apple animations that is fast enough for my taste). I know it's kind of frivolous. I also like not having to change default settings.
